language: python
python:
  - 2.7
  - 3.6
install:
  - pip install -r requirements.txt

script:
  - coverage run --source=breeze setup.py test

notifications:
  email:
    recipients:
      - alex@breezechms.com 
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

after_success: coveralls

